import dataclasses
import enum
import typing

import magicbot
import wpilib

from wpimath.geometry import Pose2d, Rotation2d, Transform2d
from wpimath.trajectory import TrajectoryGenerator, Trajectory

from subsystems.grabber import Grabber
from subsystems.arm import Arm

from components.ramsete import RamseteComponent

rdeg = Rotation2d.fromDegrees


class AType(enum.Enum):
    # Each action must specify one of the following
    TRAJECTORY = 1
    WAIT_FOR_ARM = 2

    GRAB = 3
    RELEASE = 4


@dataclasses.dataclass
class Action:
    type: AType
    arm_pos: str
    waypoints: typing.Optional[typing.List[Pose2d]] = None
    reverse: bool = False

    # Generated by the constructor
    traj: typing.Optional[Trajectory] = None


class ComplexBase(magicbot.AutonomousStateMachine):
    # All actions
    # actions: typing.List[Action]

    # Current action
    # action: typing.Optional[Action]

    # Components
    arm: Arm
    grabber: Grabber
    ramsete: RamseteComponent

    def setup(self):
        self.idx = -1
        self.action = None

        trajectory = Trajectory()

        last_waypoint = None
        for action in self.actions:
            if not action.waypoints:
                continue

            if last_waypoint:
                waypoints = [last_waypoint] + action.waypoints
            else:
                waypoints = action.waypoints

            last_waypoint = waypoints[-1]

            if action.reverse:
                cfg = self.ramsete.tconfig_rev
            else:
                cfg = self.ramsete.tconfig

            action.traj = TrajectoryGenerator.generateTrajectory(waypoints, cfg)
            trajectory += action.traj

        self.ramsete.register_autonomous_trajectory(self.MODE_NAME, trajectory)

    @magicbot.state(first=True)
    def begin_action(self):
        self.idx += 1
        if len(self.actions) == self.idx:
            self.done()
            return

        self.action = action = self.actions[self.idx]
        self.logger.info("Begin action %d", self.idx)

        # Always specifies an arm position
        if action.arm_pos == "HI":
            self.arm.gotoHi()
        elif action.arm_pos == "MID":
            self.arm.gotoMiddle()
        elif action.arm_pos == "LOW":
            self.arm.gotoLow()
        elif action.arm_pos == "NEUTRAL":
            self.arm.gotoNeutral()
        else:
            assert False

        if self.action.type == AType.RELEASE:
            self.next_state_now(self.grabber_release)
        elif self.action.type == AType.TRAJECTORY:
            self.tstate = self.ramsete.startTrajectory(action.traj)
            self.next_state_now(self.driveto)
        elif self.action.type == AType.WAIT_FOR_ARM:
            self.next_state_now(self.wait_for_arm)
        elif self.action.type == AType.GRAB:
            self.next_state_now(self.grabber_grab)
        else:
            assert False

    @magicbot.timed_state(duration=0.5, next_state="begin_action")
    def grabber_grab(self):
        self.grabber.grab()

    @magicbot.timed_state(duration=0.5, next_state="begin_action")
    def grabber_release(self):
        self.grabber.release()

    @magicbot.state()
    def driveto(self):
        if self.tstate.done:
            self.next_state_now(self.begin_action)
            return

    @magicbot.state()
    def wait_for_arm(self):
        if self.arm.getPosition() == self.action.arm_pos:
            self.next_state_now(self.begin_action)


class ScoreAndBackup(ComplexBase):
    MODE_NAME = "Score and Backup"
    DEFAULT = False

    actions = [
        # Grab
        Action(AType.GRAB, "NEUTRAL"),
        # raise to level 3
        Action(AType.WAIT_FOR_ARM, "HI"),
        # move forward slightly
        Action(
            AType.TRAJECTORY,
            "HI",
            waypoints=[
                Pose2d(0, 0, rdeg(0)),
                Pose2d(0.4, 0, rdeg(0)),
            ],
        ),
        # Release the grabber
        Action(AType.RELEASE, "HI", waypoints=[]),
        # Back up and bring the arm to zero
        Action(
            AType.TRAJECTORY,
            "NEUTRAL",
            waypoints=[
                Pose2d(0.4, 0, rdeg(0)),
                Pose2d(-4, 0, rdeg(0)),
            ],
            reverse=True,
        ),
    ]
